version: '3.3'

services:
   files:
      container_name: files
      build:
        context: server/files
        dockerfile: Dockerfile
      image: files:latest
      user: ${UID_GID}
      command: bash -c "cd /app && fastapi dev src/main.py --host 0.0.0.0"
      environment:
        - PYRIGHT_PYTHON_CACHE_DIR=/tmp
      volumes:
        - ./data:/data
        - ./server/files:/app
      ports:
        - "8000:8000"
